# Site settings
title: Rowan's Blog
description: 一个CS和自动化的爱好者
url: "https://forward-rowan.github.io"
baseurl: ""
author: "Rowan"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  posts:
    output: true
    permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
